# Site settings
title: Centymentaylia | A game
description: "A game to play."
url: "https://centymentaylia.github.io/Centymentaylia"
author:
  name: "Kerrin Paterson"
  email: "kp@example.com"
  url: "https://centymentaylia.github.ioCentymentaylia"

# Build settings
baseurl: /Centymentaylia # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
